# Generated by Django 4.2.4 on 2023-12-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_employee_options_remove_employee_type_and_more'),
        ('outerdeals', '0002_remove_officecosts_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' المبلغ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' التاريخ ')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الدين')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='  المدفوع حتى الان')),
                ('file', models.FileField(blank=True, null=True, upload_to='costs_files/', verbose_name='   فاتورة ')),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditor_user', to='userdata.user', verbose_name='  الدائن')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debtor_user', to='userdata.user', verbose_name='  المدين')),
            ],
            options={
                'verbose_name': '  تعامل  ',
                'verbose_name_plural': '  سلف وتعاملات اخرى ',
            },
        ),
        migrations.CreateModel(
            name='MonthPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' المبلغ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' التاريخ ')),
                ('file', models.FileField(blank=True, null=True, upload_to='costs_files/', verbose_name='   فاتورة ')),
                ('outdeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outerdeals.outdeals', verbose_name='  العملية')),
            ],
            options={
                'verbose_name': '  قسط  ',
                'verbose_name_plural': '  اقساط ',
            },
        ),
    ]
