# Generated by Django 4.2.4 on 2023-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outerdeals', '0003_outdeals_monthpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthpay',
            name='ammount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' المبلغ'),
        ),
        migrations.AlterField(
            model_name='outdeals',
            name='ammount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' المبلغ'),
        ),
        migrations.AlterField(
            model_name='outdeals',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='  المدفوع حتى الان'),
        ),
    ]
