# Generated by Django 5.0.6 on 2024-07-02 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outerdeals', '0004_alter_monthpay_ammount_alter_outdeals_ammount_and_more'),
        ('userdata', '0006_alter_marketsources_sourcemarket_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthpay',
            name='ammount',
            field=models.IntegerField(default=0, verbose_name=' المبلغ'),
        ),
        migrations.AlterField(
            model_name='monthpay',
            name='outdeal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outerdeals.outdeals', verbose_name='  العملية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officecosts',
            name='ammount',
            field=models.IntegerField(default=0, verbose_name=' المصروف'),
        ),
        migrations.AlterField(
            model_name='officecosts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='costs_files/', verbose_name='فاتورة '),
        ),
        migrations.AlterField(
            model_name='outdeals',
            name='ammount',
            field=models.IntegerField(default=0, verbose_name=' المبلغ'),
        ),
        migrations.AlterField(
            model_name='outdeals',
            name='creditor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creditor_user', to='userdata.user', verbose_name='  الدائن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outdeals',
            name='debtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debtor_user', to='userdata.user', verbose_name='  المدين'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outdeals',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='  المدفوع حتى الان'),
        ),
    ]
