# Generated by Django 4.2 on 2023-12-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdata', '__first__'),
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('project_address', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان المشروع')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='الخصم')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الانشاء')),
                ('is_done', models.BooleanField(default=False, verbose_name='  المشروع منتهى')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name='عميل')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkersReserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('work', models.CharField(blank=True, max_length=200, null=True, verbose_name=' العمل')),
                ('reserved_price', models.IntegerField(blank=True, null=True, verbose_name='  التكلفة المستحقة')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name=' السعر')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='  المدفوع')),
                ('main_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.categorydetail', verbose_name=' بند اساسى')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('sub_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.subcategorydetail', verbose_name=' بند فرعى')),
                ('worker', models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_did', to='userdata.employee', verbose_name=' العامل')),
            ],
            options={
                'verbose_name': '  عمل ',
                'verbose_name_plural': '  مستحقات العاملين',
            },
        ),
        migrations.CreateModel(
            name='ProjectKhamatCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('khama', models.CharField(blank=True, max_length=200, null=True, verbose_name=' الشراء')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name=' السعر')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='  المدفوع')),
                ('main_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.categorydetail', verbose_name=' بند اساسى')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.marketsources', verbose_name='المحل')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('sub_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.subcategorydetail', verbose_name=' بند فرعى')),
                ('who_paid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name='المشترى')),
            ],
            options={
                'verbose_name': '  خامة ',
                'verbose_name_plural': ' خامات المشروع',
            },
        ),
        migrations.CreateModel(
            name='ProjectCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_paid', models.CharField(blank=True, choices=[('o', 'المكتب'), ('w', 'عامل'), ('e', 'مهندس'), ('c', 'العميل')], default='o', max_length=10, null=True, verbose_name='  القائم بالدفع')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' القيمة')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('pay_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الصرف')),
                ('pay_reason_category', models.CharField(blank=True, choices=[('a', 'مصنعيات'), ('b', 'خامات')], max_length=10, null=True, verbose_name=' بند الصرف')),
                ('file', models.FileField(blank=True, null=True, upload_to='costs_files/', verbose_name='   فاتورة ')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name=' العميل')),
                ('engineers', models.ForeignKey(blank=True, limit_choices_to={'type': 'E'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineers', to='userdata.employee', verbose_name=' المهندس')),
                ('for_witch_worker', models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_worker', to='userdata.employee', verbose_name='  العامل المستلم')),
                ('main_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.categorydetail', verbose_name=' بند اساسى')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.marketsources', verbose_name=' المورد')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('sub_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.subcategorydetail', verbose_name=' بند فرعى')),
                ('workers', models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='userdata.employee', verbose_name=' العامل')),
            ],
            options={
                'verbose_name': '  مصروف ',
                'verbose_name_plural': '   مصروفات المشروع',
            },
        ),
        migrations.CreateModel(
            name='OfficeCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costtype', models.CharField(blank=True, choices=[('1', 'طلبات شغل '), ('2', 'استهلاك مكتب')], default='1', max_length=3, verbose_name='النوع')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' المصروف')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('cost_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الصرف')),
                ('paid', models.IntegerField(blank=True, default=0, null=True, verbose_name=' المدفوع')),
                ('file', models.FileField(blank=True, null=True, upload_to='costs_files/', verbose_name='   فاتورة ')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.marketsources', verbose_name='مصدر الشراء')),
            ],
            options={
                'verbose_name': '  مصروف ',
                'verbose_name_plural': ' استهلاكات المكتب ',
            },
        ),
        migrations.CreateModel(
            name='ExpectedProjectCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('workers_reserves', models.CharField(blank=True, max_length=200, null=True, verbose_name=' تفاصيل المصنعيات')),
                ('workers_reserves_cost', models.IntegerField(blank=True, null=True, verbose_name=' تكلفة المصنعيات')),
                ('build_subjects', models.CharField(blank=True, max_length=200, null=True, verbose_name=' تفاصيل الخامات')),
                ('build_subjects_cost', models.IntegerField(blank=True, null=True, verbose_name=' تكلفة الخامات')),
                ('main_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.categorydetail', verbose_name=' بند اساسى')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('sub_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.subcategorydetail', verbose_name=' بند فرعى')),
            ],
            options={
                'verbose_name': '  مصروف ',
                'verbose_name_plural': ' المصروفات المتوقعة للمشروع',
            },
        ),
    ]
