# Generated by Django 4.2.4 on 2023-11-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البند ')),
            ],
            options={
                'verbose_name': 'بند فرعى',
                'verbose_name_plural': '   البنود فرعية',
            },
        ),
        migrations.CreateModel(
            name='DesignWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغلانة ')),
                ('unit_price', models.IntegerField(blank=True, default=1, null=True, verbose_name=' سعر الوحدة')),
                ('mitr_price', models.IntegerField(blank=True, default=1, null=True, verbose_name=' سعر المتر')),
            ],
            options={
                'verbose_name': 'شغلانة',
                'verbose_name_plural': ' انواع شغل التصميم',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name=' التصنيف')),
                ('category_type', models.CharField(blank=True, choices=[('E', 'هندسى'), ('T', 'فنى')], default='T', max_length=10, verbose_name='نوع التصنيف')),
            ],
            options={
                'verbose_name': ' تصنيف',
                'verbose_name_plural': '   تصنيف الموظفين ',
            },
        ),
        migrations.CreateModel(
            name='MarketSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcemarket', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': ' مورد',
                'verbose_name_plural': ' موردين',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المشروع')),
                ('project_address', models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان المشروع')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='الخصم')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الانشاء')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومى')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظات')),
                ('code', models.CharField(blank=True, editable=False, max_length=12, null=True, verbose_name='الكود')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maindata.user')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
            bases=('maindata.user',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maindata.user')),
                ('type', models.CharField(blank=True, choices=[('E', 'مهندس'), ('W', 'عامل')], default='W', max_length=10, verbose_name='النوع')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.employeecategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
            },
            bases=('maindata.user',),
        ),
        migrations.CreateModel(
            name='OfficeCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costtype', models.CharField(blank=True, choices=[('1', 'طلبات شغل '), ('2', 'استهلاك مكتب')], default='1', max_length=3, verbose_name='النوع')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' المصروف')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('cost_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الصرف')),
                ('paid', models.IntegerField(blank=True, default=0, null=True, verbose_name=' المدفوع')),
                ('file', models.FileField(blank=True, null=True, upload_to='costs_files/', verbose_name='   فاتورة ')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.marketsources', verbose_name='مصدر الشراء')),
            ],
            options={
                'verbose_name': '  مصروف ',
                'verbose_name_plural': ' استهلاكات المكتب ',
            },
        ),
        migrations.CreateModel(
            name='inPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='دفعة مالية')),
                ('giver', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسلم')),
                ('recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='المستلم')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
                ('file', models.FileField(blank=True, null=True, upload_to='inpay_files/', verbose_name='   فاتورة ')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': '  دفعة مالية',
                'verbose_name_plural': ' الوارد المالى',
            },
        ),
        migrations.CreateModel(
            name='EngSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_way', models.CharField(blank=True, choices=[('direct', 'مقطعية'), ('percent', 'نسبة')], default='mitr', max_length=10, verbose_name='نوع الحسبة')),
                ('ammount', models.IntegerField(blank=True, default=0, null=True, verbose_name='الكمية')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الاضافة')),
                ('all_costs', models.IntegerField(blank=True, default=1, editable=False, null=True, verbose_name=' جميع التكاليف')),
                ('work_cost', models.IntegerField(blank=True, default=1, editable=False, null=True, verbose_name=' الحساب المستحق')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': '  عمل',
                'verbose_name_plural': ' اعمال التصميم الخاصة بالمشاريع ',
            },
        ),
        migrations.CreateModel(
            name='DesignWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_way', models.CharField(blank=True, choices=[('direct', 'مقطعية'), ('mitr', 'بالمتر'), ('unit', 'بالوحدة')], default='mitr', max_length=10, verbose_name='نوع الحسبة')),
                ('ammount', models.IntegerField(blank=True, default=0, null=True, verbose_name='الكمية')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الاضافة')),
                ('work_cost', models.IntegerField(blank=True, default=1, editable=False, null=True, verbose_name=' المجموع')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('worktype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.designworktype', verbose_name='نوع الشغلانة')),
            ],
            options={
                'verbose_name': '  عمل',
                'verbose_name_plural': ' اعمال التصميم الخاصة بالمشاريع ',
            },
        ),
        migrations.CreateModel(
            name='ProjectCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_paid', models.CharField(blank=True, choices=[('o', 'المكتب'), ('w', 'عامل'), ('e', 'مهندس'), ('c', 'العميل')], default='o', max_length=10, null=True, verbose_name='  القائم بالدفع')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' القيمة')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('pay_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الصرف')),
                ('pay_reason_category', models.CharField(blank=True, choices=[('a', 'مصنعيات'), ('b', 'خامات')], max_length=10, null=True, verbose_name=' بند الصرف')),
                ('file', models.FileField(blank=True, null=True, upload_to='costs_files/', verbose_name='   فاتورة ')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.marketsources', verbose_name=' المورد')),
                ('pay_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.categorydetail', verbose_name='تفصيل البند')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.client', verbose_name=' العميل')),
            ],
            options={
                'verbose_name': '  مصروف ',
                'verbose_name_plural': '   مصروفات المشروع',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.client', verbose_name='عميل'),
        ),
        migrations.CreateModel(
            name='OutPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' القيمة')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('pay_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الصرف')),
                ('file', models.FileField(blank=True, null=True, upload_to='out_pay_files/', verbose_name='   فاتورة ')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.employee', verbose_name='القائم بالسحب')),
            ],
            options={
                'verbose_name': ' عملية سحب ',
                'verbose_name_plural': ' قائمة السحب من الخزينة',
            },
        ),
    ]
