# Generated by Django 4.2 on 2023-12-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_alter_user_options'),
        ('maindata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='دفعة مالية')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
                ('file', models.FileField(blank=True, null=True, upload_to='inpay_files/', verbose_name='   فاتورة ')),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name='المسلم')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpaypro', to='maindata.project', verbose_name='المشروع')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipant', to='userdata.user', verbose_name='المستلم')),
            ],
            options={
                'verbose_name': '  دفعة مالية',
                'verbose_name_plural': ' الوارد المالى',
            },
        ),
    ]
