# Generated by Django 4.2.4 on 2023-11-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0002_projectcosts_engineers_projectcosts_workers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engsupervision',
            options={'verbose_name': '  عمل', 'verbose_name_plural': ' اعمال الاشراف الهندسى الخاصة بالمشاريع '},
        ),
        migrations.AlterField(
            model_name='projectcosts',
            name='engineers',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'E'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineers', to='maindata.employee', verbose_name=' المهندس'),
        ),
        migrations.AlterField(
            model_name='projectcosts',
            name='workers',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='maindata.employee', verbose_name=' العامل'),
        ),
    ]
