# Generated by Django 4.2 on 2023-12-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_employee_options_remove_employee_type_and_more'),
        ('maindata', '0002_inpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcosts',
            name='engineers',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'E'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineers', to='userdata.user', verbose_name=' المهندس'),
        ),
        migrations.AlterField(
            model_name='projectcosts',
            name='for_witch_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_worker', to='userdata.user', verbose_name='  العامل المستلم'),
        ),
        migrations.AlterField(
            model_name='projectcosts',
            name='workers',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='userdata.user', verbose_name=' العامل'),
        ),
        migrations.AlterField(
            model_name='projectworkersreserves',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_did', to='userdata.user', verbose_name=' العامل'),
        ),
    ]
