# Generated by Django 4.2 on 2023-12-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_employee_options_remove_employee_type_and_more'),
        ('maindata', '0003_alter_projectcosts_engineers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'C'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name='عميل'),
        ),
    ]
