# Generated by Django 4.2.4 on 2023-11-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0003_alter_engsupervision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم المشروع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcosts',
            name='pay_category_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.categorydetail', verbose_name=' بند فرعى'),
        ),
    ]
