# Generated by Django 4.2.4 on 2023-11-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0005_project_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
