# Generated by Django 4.2.4 on 2023-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0005_alter_inpay_giver_delete_projectcosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectworkersreserves',
            name='reserved_price',
        ),
        migrations.AlterField(
            model_name='projectworkersreserves',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='  التكلفة المستحقة'),
        ),
    ]
