# Generated by Django 4.2.4 on 2023-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0006_alter_project_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='  المشروع منتهى'),
        ),
    ]
