# Generated by Django 4.2.4 on 2023-12-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0006_remove_projectworkersreserves_reserved_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeCosts',
        ),
    ]
