# Generated by Django 4.2.4 on 2023-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0007_delete_officecosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectkhamatcosts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='khamat_files/', verbose_name='   فاتورة '),
        ),
    ]
