# Generated by Django 4.2.4 on 2023-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0007_alter_project_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='designwork',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' وصف'),
        ),
    ]
