# Generated by Django 4.2 on 2023-11-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0009_projectcosts_for_witch_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutPay',
            new_name='MoneyWithDraw',
        ),
    ]
