# Generated by Django 4.2.4 on 2023-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0009_alter_projectkhamatcosts_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedprojectcosts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='expectedcostsfiles/', verbose_name='   ملف '),
        ),
        migrations.AddField(
            model_name='expectedprojectcosts',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات'),
        ),
        migrations.AddField(
            model_name='inpay',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات'),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات'),
        ),
        migrations.AddField(
            model_name='projectkhamatcosts',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات'),
        ),
        migrations.AddField(
            model_name='projectworkersreserves',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='   ملف '),
        ),
        migrations.AddField(
            model_name='projectworkersreserves',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات'),
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='khama',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' التوصيف'),
        ),
    ]
