# Generated by Django 4.2 on 2023-11-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0010_rename_outpay_moneywithdraw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydetail',
            options={'verbose_name': 'بند اساسى', 'verbose_name_plural': '   البنود الاساسية'},
        ),
        migrations.AlterModelOptions(
            name='moneywithdraw',
            options={'verbose_name': ' عملية سحب ', 'verbose_name_plural': '  السحب من الخزينة'},
        ),
        migrations.RenameField(
            model_name='categorydetail',
            old_name='pay_category',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='projectcosts',
            old_name='pay_category_detail',
            new_name='main_category_detail',
        ),
        migrations.CreateModel(
            name='SubCategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البند ')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.categorydetail', verbose_name='البند الاساسى')),
            ],
            options={
                'verbose_name': 'بند فرعى',
                'verbose_name_plural': '   البنود الفرعية',
            },
        ),
    ]
