# Generated by Django 4.2 on 2023-11-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0011_alter_categorydetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcosts',
            name='sub_category_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.subcategorydetail', verbose_name=' بند فرعى'),
        ),
        migrations.AlterField(
            model_name='projectcosts',
            name='main_category_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.categorydetail', verbose_name=' بند اساسى'),
        ),
    ]
