# Generated by Django 4.2.4 on 2023-11-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0012_projectcosts_sub_category_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedProjectCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('workers_reserves', models.CharField(blank=True, max_length=200, null=True, verbose_name=' تفاصيل المصنعيات')),
                ('workers_reserves_cost', models.CharField(blank=True, max_length=200, null=True, verbose_name=' تكلفة المصنعيات')),
                ('build_subjects', models.CharField(blank=True, max_length=200, null=True, verbose_name=' تفاصيل الخامات')),
                ('build_subjects_cost', models.CharField(blank=True, max_length=200, null=True, verbose_name=' تكلفة الخامات')),
                ('main_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.categorydetail', verbose_name=' بند اساسى')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('sub_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.subcategorydetail', verbose_name=' بند فرعى')),
            ],
            options={
                'verbose_name': '  مصروف ',
                'verbose_name_plural': ' المصروفات المتوقعة للمشروع',
            },
        ),
    ]
