# Generated by Django 4.2.4 on 2023-12-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0013_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.coin', verbose_name='عملة التعامل'),
        ),
    ]
