# Generated by Django 4.2.4 on 2023-11-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0014_alter_expectedprojectcosts_build_subjects_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedprojectcosts',
            name='build_subjects_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name=' تكلفة الخامات'),
        ),
        migrations.AlterField(
            model_name='expectedprojectcosts',
            name='workers_reserves_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name=' تكلفة المصنعيات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.user', verbose_name='عميل'),
        ),
    ]
