# Generated by Django 4.2.4 on 2023-12-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0014_project_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectkhamatcosts',
            name='khama_current_price',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='  سعر الخامة وقت الشراء'),
        ),
    ]
