# Generated by Django 4.2.4 on 2023-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0015_projectkhamatcosts_khama_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='---', max_length=200, verbose_name='اسم المشروع'),
        ),
    ]
