# Generated by Django 4.2.4 on 2023-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0016_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(blank=True, choices=[('G', 'عام'), ('E', 'مهندس'), ('W', 'عامل')], default='G', max_length=10, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='employeecategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('G', 'عام'), ('E', 'هندسى'), ('T', 'فنى')], default='T', max_length=10, verbose_name='نوع التصنيف'),
        ),
    ]
