# Generated by Django 4.2.4 on 2023-12-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0016_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedprojectcosts',
            name='total_cost_for_this_khama',
            field=models.IntegerField(blank=True, help_text='yyyyyyyyy', null=True, verbose_name='  المجموع'),
        ),
    ]
