# Generated by Django 4.2.4 on 2023-11-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0017_alter_employee_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKhamatCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('main_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.categorydetail', verbose_name=' بند اساسى')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('sub_category_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.subcategorydetail', verbose_name=' بند فرعى')),
            ],
            options={
                'verbose_name': '  خامة ',
                'verbose_name_plural': ' خامات المشروع',
            },
        ),
    ]
