# Generated by Django 4.2.4 on 2023-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0018_alter_expectedprojectcosts_total_cost_for_this_khama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedprojectcosts',
            name='total_cost_for_this_khama',
            field=models.IntegerField(blank=True, help_text='حاصل ضرب سعر الوحدة للمنتج فى الكمية (سعر المنتج الحالى)', null=True, verbose_name='  المجموع'),
        ),
    ]
