# Generated by Django 4.2.4 on 2023-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0019_alter_expectedprojectcosts_build_subjects_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedprojectcosts',
            name='build_subjects_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name=' تكلفة الخامات'),
        ),
        migrations.AlterField(
            model_name='expectedprojectcosts',
            name='workers_reserves_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name=' تكلفة المصنعيات'),
        ),
    ]
