# Generated by Django 4.2.4 on 2023-12-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0020_inpay_project_khamat_costs_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coin',
            field=models.ForeignKey(blank=True, help_text='تعنى ان جميع الحسابات والارقام الحسابية المسجلة هى بهذه العمله', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.coin', verbose_name='عملة التعامل'),
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='khama_current_price',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='  سعر الخامة وقت الشراء'),
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='  المدفوع'),
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='  الكمية'),
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='total_cost_for_this_khama',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='  المجموع'),
        ),
    ]
