# Generated by Django 5.0 on 2023-12-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0021_alter_project_coin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedprojectcosts',
            name='total_cost_for_this_khama',
            field=models.IntegerField(blank=True, help_text='حاصل ضرب سعر الوحدة للمنتج فى الكمية (  اخر سعر تم اضافته او تعديله للمنتج )', null=True, verbose_name='  المجموع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coin',
            field=models.ForeignKey(blank=True, help_text='تعنى ان جميع الحسابات والارقام الحسابية المسجلة فى هذا المشروع هى بهذه العمله', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.coin', verbose_name='عملة التعامل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False, help_text='اختيار هذا المربع (تظليلة بالازرق) يعنى ان هذا المشروع تم الانتهاء منه', verbose_name='  المشروع منتهى'),
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='total_cost_for_this_khama',
            field=models.IntegerField(blank=True, default=0, help_text='عبارة عن حاصل ضرب الكمية فى سعر الوحده للخامة (لاحظ : تتم المحاسبة على سعر الوحده الحالى للمنتج لكن اذا تم تغير سعر المنتج لاحقا لن ينطبق هذا التغيير على الصفوف المسجلة مسبقا ولكن ينطبق على اى صف جديد يتم اضافته, لذلك اذا تم شراء خامة بسعر معين وتم اضافتها ثم تم شراء نفس الخامة فى وقت لاحق وكان سعر الخامة قد تغير يجب اضافة عملية الشراء الجديدة كصف مستقل بدلا من تعديل الكمية فى الصف القديم لان اذا عدلت الكمية فسيحسب المجموع بناء على السعر القديم )', null=True, verbose_name='  المجموع'),
        ),
    ]
