# Generated by Django 5.0 on 2023-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0022_alter_expectedprojectcosts_total_cost_for_this_khama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkersreserves',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='  المدفوع'),
        ),
        migrations.AlterField(
            model_name='projectworkersreserves',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='  التكلفة المستحقة'),
        ),
    ]
