# Generated by Django 4.2.4 on 2023-12-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_employee_options_remove_employee_type_and_more'),
        ('maindata', '0023_alter_projectworkersreserves_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediaryTableWorkerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directlyarrived', models.IntegerField(blank=True, default=0, null=True, verbose_name=' المدفوع')),
                ('charge_reserved', models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى باقى المستحق')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('file', models.FileField(blank=True, null=True, upload_to='WorkerCount_files/', verbose_name='   فاتورة ')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('worker', models.ForeignKey(blank=True, limit_choices_to={'type': 'W'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name='العامل')),
            ],
            options={
                'verbose_name': '  تعامل ',
                'verbose_name_plural': ' تخليص حسابات العمال',
            },
        ),
    ]
