# Generated by Django 4.2.4 on 2023-12-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0025_intermediarytableworkercount_total_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediarytableworkercount',
            name='total_paid_until_now',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى المدفوع الى الان'),
        ),
    ]
