# Generated by Django 4.2.4 on 2023-12-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0026_intermediarytableworkercount_total_paid_until_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediarytableworkercount',
            name='directlyarrived',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' القيمة المراد دفعها'),
        ),
    ]
