# Generated by Django 4.2.4 on 2023-12-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0028_intermediarytablemarketcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intermediarytablemarketcount',
            options={'verbose_name': '  تعامل ', 'verbose_name_plural': ' تخليص حسابات الموردين'},
        ),
    ]
