# Generated by Django 4.2.4 on 2023-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0029_alter_intermediarytablemarketcount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediarytablemarketcount',
            name='charge_reserved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى باقى المستحق'),
        ),
        migrations.AddField(
            model_name='intermediarytablemarketcount',
            name='total_paid_until_now',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى المدفوع الى الان'),
        ),
        migrations.AddField(
            model_name='intermediarytablemarketcount',
            name='total_reserved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى المستحق'),
        ),
    ]
