# Generated by Django 4.2.4 on 2024-01-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0030_intermediarytablemarketcount_charge_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isdesignwork',
            field=models.BooleanField(blank=True, null=True, verbose_name='المشروع يتضمن اعمال تصميم ؟ '),
        ),
        migrations.AddField(
            model_name='project',
            name='issupervision',
            field=models.BooleanField(blank=True, null=True, verbose_name='المشروع يتضمن اعمال اشراف ؟'),
        ),
    ]
