# Generated by Django 4.2.4 on 2024-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0031_project_isdesignwork_project_issupervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isdesignwork',
            field=models.BooleanField(default=False, verbose_name='المشروع يتضمن اعمال تصميم ؟ '),
        ),
        migrations.AlterField(
            model_name='project',
            name='issupervision',
            field=models.BooleanField(default=False, verbose_name='المشروع يتضمن اعمال اشراف ؟'),
        ),
    ]
