# Generated by Django 4.2.4 on 2024-01-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0036_inpay_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpay',
            name='total_paid',
        ),
    ]
