# Generated by Django 4.2.4 on 2024-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0037_remove_inpay_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_address',
            field=models.CharField(blank=True, help_text='ان ترك خاليا سيأخذ عنوان العميل عند الحفظ', max_length=200, null=True, verbose_name=' عنوان المشروع'),
        ),
    ]
