# Generated by Django 4.2.4 on 2024-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0038_alter_project_project_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(default='---', max_length=200, verbose_name='اسم المشروع'),
        ),
    ]
