# Generated by Django 4.2.4 on 2024-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0039_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' عنوان المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(default='---', max_length=200, verbose_name=',وصف المشروع'),
        ),
    ]
