# Generated by Django 5.0.6 on 2024-07-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0040_alter_project_project_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpay',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='دفعة مالية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inpay',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inpaypro', to='maindata.project', verbose_name='المشروع'),
            preserve_default=False,
        ),
    ]
