# Generated by Django 5.0.6 on 2024-07-03 00:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0041_alter_inpay_paid_alter_inpay_project'),
        ('subdata', '0003_alter_categorydetail_main_category_alter_khama_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='khama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subdata.khama', verbose_name='خامة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='paid',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='  المدفوع'),
        ),
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='  الكمية'),
        ),
    ]
