# Generated by Django 5.0.6 on 2024-07-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0043_alter_expectedprojectcosts_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectkhamatcosts',
            name='total_cost_for_this_khama',
            field=models.IntegerField(blank=True, default=0, help_text='عبارة عن حاصل ضرب الكمية فى سعر الوحده للخامة (لاحظ : تتم المحاسبة على سعر الوحده الحالى للمنتج لكن اذا تم تغير سعر المنتج لاحقا لن ينطبق هذا التغيير على الصفوف المسجلة مسبقا ولكن ينطبق على اى صف جديد يتم اضافته, لذلك اذا تم شراء خامة بسعر معين وتم اضافتها ثم تم شراء نفس الخامة فى وقت لاحق وكان سعر الخامة قد تغير يجب اضافة عملية الشراء الجديدة كصف مستقل بدلا من تعديل الكمية فى الصف القديم لان اذا عدلت الكمية فسيحسب المجموع بناء على السعر القديم )', null=True, verbose_name='  المجموع'),
        ),
    ]
