# Generated by Django 5.0.6 on 2024-07-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0044_alter_projectkhamatcosts_total_cost_for_this_khama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediarytablemarketcount',
            name='charge_reserved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى باقى المستحق'),
        ),
        migrations.AlterField(
            model_name='intermediarytablemarketcount',
            name='total_paid_until_now',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى المدفوع الى الان'),
        ),
        migrations.AlterField(
            model_name='intermediarytablemarketcount',
            name='total_reserved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' اجمالى المستحق'),
        ),
    ]
