# Generated by Django 5.0.6 on 2024-07-03 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0045_alter_intermediarytablemarketcount_charge_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinValueValidator(1)], verbose_name=',وصف المشروع'),
        ),
    ]
