# Generated by Django 5.0.6 on 2024-07-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0046_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(max_length=200, verbose_name=',وصف المشروع'),
        ),
    ]
