# Generated by Django 5.0.6 on 2024-07-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0047_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(max_length=200, verbose_name='وصف المشروع'),
        ),
    ]
