# Generated by Django 4.2 on 2023-12-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0001_initial'),
        ('maindata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyWithDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name=' القيمة')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الصرف')),
                ('pay_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='سبب الصرف')),
                ('file', models.FileField(blank=True, null=True, upload_to='out_pay_files/', verbose_name='   فاتورة ')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.employee', verbose_name='القائم بالسحب')),
            ],
            options={
                'verbose_name': ' عملية سحب ',
                'verbose_name_plural': '  السحب من الخزينة',
            },
        ),
        migrations.CreateModel(
            name='inPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='دفعة مالية')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
                ('file', models.FileField(blank=True, null=True, upload_to='inpay_files/', verbose_name='   فاتورة ')),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name='المسلم')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpaypro', to='maindata.project', verbose_name='المشروع')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipant', to='userdata.user', verbose_name='المستلم')),
            ],
            options={
                'verbose_name': '  دفعة مالية',
                'verbose_name_plural': ' الوارد المالى',
            },
        ),
    ]
