# Generated by Django 4.2.4 on 2023-12-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inoutpay', '0003_coin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
