# Generated by Django 4.2 on 2023-12-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البند ')),
            ],
            options={
                'verbose_name': 'بند اساسى',
                'verbose_name_plural': '   البنود',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name=' التصنيف')),
                ('category_type', models.CharField(blank=True, choices=[('G', 'عام'), ('E', 'هندسى'), ('T', 'فنى')], default='T', max_length=10, verbose_name='نوع التصنيف')),
            ],
            options={
                'verbose_name': ' تصنيف',
                'verbose_name_plural': '   تصنيف الموظفين ',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البند ')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.categorydetail', verbose_name='البند الاساسى')),
            ],
            options={
                'verbose_name': 'بند فرعى',
                'verbose_name_plural': '   البنود الفرعية',
            },
        ),
    ]
