# Generated by Django 4.2.4 on 2023-12-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الخامة ')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='سعر الوحده ')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.categorydetail', verbose_name='البند الاساسى')),
            ],
            options={
                'verbose_name': ' خامة',
                'verbose_name_plural': ' الخامات',
            },
        ),
    ]
