# Generated by Django 5.0.6 on 2024-07-02 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdata', '0002_khama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetail',
            name='main_category',
            field=models.CharField(default='', max_length=100, verbose_name='اسم البند '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khama',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='اسم الخامة '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategorydetail',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subdata.categorydetail', verbose_name='البند الاساسى'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategorydetail',
            name='sub_category',
            field=models.CharField(default='', max_length=100, verbose_name='اسم البند '),
            preserve_default=False,
        ),
    ]
