# Generated by Django 5.0.6 on 2024-07-03 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdata', '0003_alter_categorydetail_main_category_alter_khama_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khama',
            name='unit_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحده '),
        ),
    ]
