# Generated by Django 5.0.6 on 2024-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name=' الاسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name=' الموبايل'),
            preserve_default=False,
        ),
    ]
