# Generated by Django 4.2.4 on 2023-12-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finishcount', '0002_workercount_charge_reserved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workercount',
            name='charge_reserved',
        ),
    ]
