# Generated by Django 4.2.4 on 2023-12-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finishcount', '0004_intermediarytableworkercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntermediaryTableWorkerCount',
        ),
    ]
