# Generated by Django 4.2 on 2023-12-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maindata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغلانة ')),
                ('unit_price', models.IntegerField(blank=True, default=1, null=True, verbose_name=' سعر الوحدة')),
                ('mitr_price', models.IntegerField(blank=True, default=1, null=True, verbose_name=' سعر المتر')),
            ],
            options={
                'verbose_name': 'شغلانة',
                'verbose_name_plural': ' انواع شغل التصميم',
            },
        ),
        migrations.CreateModel(
            name='EngSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_way', models.CharField(blank=True, choices=[('direct', 'مقطعية'), ('percent', 'نسبة')], default='mitr', max_length=10, verbose_name='نوع الحسبة')),
                ('ammount', models.IntegerField(blank=True, default=0, null=True, verbose_name='الكمية')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الاضافة')),
                ('all_costs', models.IntegerField(blank=True, default=1, editable=False, null=True, verbose_name=' جميع التكاليف')),
                ('work_cost', models.IntegerField(blank=True, default=1, editable=False, null=True, verbose_name=' الحساب المستحق')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name=' وصف')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': '  عمل',
                'verbose_name_plural': ' اعمال الاشراف الهندسى ',
            },
        ),
        migrations.CreateModel(
            name='DesignWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_way', models.CharField(blank=True, choices=[('direct', 'مقطعية'), ('mitr', 'بالمتر'), ('unit', 'بالوحدة')], default='mitr', max_length=10, verbose_name='نوع الحسبة')),
                ('ammount', models.IntegerField(blank=True, default=0, null=True, verbose_name='الكمية')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الاضافة')),
                ('work_cost', models.IntegerField(blank=True, default=1, editable=False, null=True, verbose_name=' المجموع')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name=' وصف')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع')),
                ('worktype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksdata.designworktype', verbose_name='نوع الشغلانة')),
            ],
            options={
                'verbose_name': '  عمل',
                'verbose_name_plural': ' اعمال التصميم   ',
            },
        ),
    ]
