# Generated by Django 4.2.4 on 2023-12-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engsupervision',
            name='account_way',
            field=models.CharField(blank=True, choices=[('direct', 'مقطعية'), ('percent', 'نسبة')], default='direct', max_length=10, verbose_name='نوع الحسبة'),
        ),
        migrations.AlterField(
            model_name='engsupervision',
            name='ammount',
            field=models.IntegerField(blank=True, null=True, verbose_name='الكمية'),
        ),
    ]
