# Generated by Django 4.2.4 on 2023-12-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0002_alter_engsupervision_account_way_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='   ملف '),
        ),
        migrations.AddField(
            model_name='designwork',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات'),
        ),
    ]
