# Generated by Django 4.2.4 on 2023-12-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0016_alter_project_project_name'),
        ('worksdata', '0003_designwork_file_designwork_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engsupervision',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.project', verbose_name='المشروع'),
        ),
    ]
