# Generated by Django 4.2.4 on 2023-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0004_alter_engsupervision_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engsupervision',
            options={'verbose_name': '  عمل', 'verbose_name_plural': ' حسبة الاشراف الهندسى '},
        ),
        migrations.AlterField(
            model_name='designworktype',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='شغلانة '),
        ),
    ]
