# Generated by Django 4.2.4 on 2023-12-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0005_alter_engsupervision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designwork',
            name='work_cost',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name=' المجموع'),
        ),
    ]
