# Generated by Django 5.0 on 2023-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0006_alter_designwork_work_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designwork',
            name='account_way',
            field=models.CharField(blank=True, choices=[('direct', 'مقطعية'), ('mitr', 'بالمتر'), ('unit', 'بالوحدة')], default='mitr', help_text='اختيار بالمتر معناه ان سيتم احتساب سعر التصميم عن طريق ضرب الكمية فى سعر المتر الواحد للشغلانة , اختيار بالوحده يعنى سعر التصميم يساوى ضرب الكمية فى سعر الوحدة للشغلانة , اختيار مقطعية يعنى سعر التصميم يساوى الكمية مباشرة', max_length=10, verbose_name='نوع الحسبة'),
        ),
        migrations.AlterField(
            model_name='engsupervision',
            name='account_way',
            field=models.CharField(blank=True, choices=[('direct', 'مقطعية'), ('percent', 'نسبة')], default='direct', help_text='اختيار نسبة معناه ان سيتم احتساب سعر الاشراف عن طريق ضرب الكمية (%) فى ( مجموع حساب الخامات الفعلية + مجموع حساب مستحقات العاملين ) مقسوما على 100 , اختيار مقطعية يعنى سعر الاشراف يساوى الكمية مباشرة', max_length=10, verbose_name='نوع الحسبة'),
        ),
    ]
