# Generated by Django 4.2.4 on 2024-01-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0007_alter_designwork_account_way_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designwork',
            name='designwork_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' السعر الكلى للشغلانة'),
        ),
    ]
