# Generated by Django 4.2.4 on 2024-01-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0008_designwork_designwork_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designwork',
            name='designwork_total_price',
        ),
    ]
