# Generated by Django 4.2.4 on 2024-01-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0009_remove_designwork_designwork_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designwork',
            name='work_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' المجموع'),
        ),
    ]
