# Generated by Django 5.0.6 on 2024-07-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0041_alter_inpay_paid_alter_inpay_project'),
        ('worksdata', '0010_alter_designwork_work_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designwork',
            name='ammount',
            field=models.IntegerField(default=0, verbose_name='الكمية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designwork',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maindata.project', verbose_name='المشروع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designwork',
            name='worktype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worksdata.designworktype', verbose_name='نوع الشغلانة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designworktype',
            name='mitr_price',
            field=models.IntegerField(default=1, verbose_name=' سعر المتر'),
        ),
        migrations.AlterField(
            model_name='designworktype',
            name='type',
            field=models.CharField(default=1, max_length=100, verbose_name='شغلانة '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designworktype',
            name='unit_price',
            field=models.IntegerField(default=1, verbose_name=' سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='engsupervision',
            name='ammount',
            field=models.IntegerField(default=0, verbose_name='الكمية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engsupervision',
            name='project',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to='maindata.project', verbose_name='المشروع'),
            preserve_default=False,
        ),
    ]
