# Generated by Django 5.0.6 on 2024-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0011_alter_designwork_ammount_alter_designwork_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designwork',
            name='work_cost',
            field=models.IntegerField(default=0, verbose_name=' المجموع'),
        ),
    ]
