# Generated by Django 5.0.6 on 2024-07-03 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0014_alter_designwork_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designwork',
            name='work_cost',
            field=models.IntegerField(default=0, verbose_name=' المجموع'),
        ),
        migrations.AlterField(
            model_name='designworktype',
            name='mitr_price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name=' سعر المتر'),
        ),
        migrations.AlterField(
            model_name='designworktype',
            name='unit_price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name=' سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='engsupervision',
            name='ammount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية'),
        ),
    ]
