# Generated by Django 5.0.6 on 2024-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksdata', '0016_alter_designwork_work_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engsupervision',
            name='work_cost',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=' الحساب المستحق'),
        ),
    ]
