# Generated by Django 4.2 on 2023-12-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdata', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcemarket', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': ' مورد',
                'verbose_name_plural': ' موردين',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومى')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظات')),
                ('code', models.CharField(blank=True, editable=False, max_length=12, null=True, verbose_name='الكود')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('G', 'عام'), ('E', 'مهندس'), ('W', 'عامل')], default='G', max_length=10, null=True, verbose_name='النوع')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdata.employeecategory', verbose_name='التصنيف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdata.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
            },
        ),
    ]
