# Generated by Django 4.2 on 2023-12-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'بيانات اضافية للموظف', 'verbose_name_plural': 'بيانات اضافية للموظفين'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('C', 'عميل'), ('E', 'مهندس'), ('W', 'عامل')], default='C', max_length=10, null=True, verbose_name='النوع'),
        ),
    ]
