# Generated by Django 5.0.6 on 2024-07-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_remove_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsources',
            name='sourcemarket',
            field=models.CharField(default='', max_length=200, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='الاسم'),
            preserve_default=False,
        ),
    ]
