# Generated by Django 5.0.6 on 2024-07-03 20:04

import userdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_alter_marketsources_sourcemarket_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, validators=[userdata.models.validate_name_length], verbose_name='الاسم'),
        ),
    ]
